# Node.js


# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm install'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-connection'
    organization: 'hieunv49'
    scannerMode: 'MSBuild'
    projectKey: 'HieuNV49_sonar-demo'
    projectName: 'sonar-demo'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'npm run build.azure'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'